### ISSUE TITLE
Old weblink

### ISSUE THREAD

**Issue by bemattmann** [SLUB-digitalpreservation/mediaconch-profile#1]
The weblink to the SLUB policy in the README-File is out of date:

> Hint: the policy is not officially released, please check http://www.slub-dresden.de/ueber-uns/slubarchiv/technische-standards-fuer-die-ablieferung-von-digitalen-dokumenten/langzeitarchivfaehige-dateiformate/ for release information.

**Comment by DasFaultier** [comment]
Due to internal policy, this GitHub repo is no longer actively maintained. You can find all relevant information at https://slubarchiv.slub-dresden.de/technische-standards-fuer-die-ablieferung-von-digitalen-dokumenten/, where it's updated bi-annually (following a fixed release schedule).
